# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  lane :unittest do
      schemeName = "QuizApp"#ENV['FASTLANE_SCHEME_NAME']
      scan(scheme: schemeName, device:"iPhone 15 Pro",  sdk:"iphonesimulator")#, suppress_xcode_output:false)
    #else
      puts("Testing is disabled for #{ENV['FASTLANE_SCHEME_NAME']}")
    #end
  end
end
